const fs = require('fs');
const path = require('path');

const bookTitle = 'The Friction of the Spark';
const repoRoot = path.resolve(__dirname, '..');
const projectRoot = path.resolve(repoRoot, '..');
const contentDir = path.join(repoRoot, 'Content', 'TheFrictionOfTheSpark');
const englishSourcePath = path.join(contentDir, 'en.txt');
const chineseSourcePath = path.join(contentDir, 'cn.txt');
const readerDataPath = path.join(repoRoot, 'src', 'features', 'reader', 'data.js');
const auditPath = path.join(contentDir, 'AUDIT.md');

const rewriteSources = [
    path.join(projectRoot, 'rewrites', 'chapters-01-03.md'),
    path.join(projectRoot, 'rewrites', 'chapters-04-06.md'),
    path.join(projectRoot, 'rewrites', 'chapters-07-09.md'),
    ...Array.from({ length: 15 }, (_, index) => path.join(projectRoot, 'rewrites', `chapter-${index + 10}.md`))
];

function escapeHtml(value) {
    return value
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}

function inlineMarkdownToHtml(value) {
    return escapeHtml(value)
        .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
}

function bodyToHtml(body) {
    return body
        .trim()
        .split(/\n{2,}/)
        .map((paragraph) => paragraph.replace(/\s*\n\s*/g, ' ').trim())
        .filter(Boolean)
        .map((paragraph) => `<p>${inlineMarkdownToHtml(paragraph)}</p>`)
        .join('\n');
}

function parseRewriteFile(filePath) {
    const source = fs.readFileSync(filePath, 'utf8').replace(/\r\n/g, '\n');
    const chapterRegex = /^## Chapter (\d+): ([^\n]+)\n([\s\S]*?)(?=^## Chapter \d+: |(?![\s\S]))/gm;
    const chapters = [];
    let match;

    while ((match = chapterRegex.exec(source)) !== null) {
        chapters.push({
            chapter: Number(match[1]),
            title: `Chapter ${match[1]}: ${match[2].trim()}`,
            body: match[3].trim()
        });
    }

    return chapters;
}

function loadChaptersFromRewrites() {
    if (!rewriteSources.every((sourcePath) => fs.existsSync(sourcePath))) {
        return null;
    }

    return rewriteSources.flatMap(parseRewriteFile).sort((a, b) => a.chapter - b.chapter);
}

function parseEnglishSource() {
    if (!fs.existsSync(englishSourcePath)) {
        throw new Error(`Missing English source: ${englishSourcePath}`);
    }

    const source = fs.readFileSync(englishSourcePath, 'utf8').replace(/\r\n/g, '\n');
    const chapterRegex = /^## Chapter (\d+): ([^\n]+)\n([\s\S]*?)(?=^## Chapter \d+: |(?![\s\S]))/gm;
    const chapters = [];
    let match;

    while ((match = chapterRegex.exec(source)) !== null) {
        chapters.push({
            chapter: Number(match[1]),
            title: `Chapter ${match[1]}: ${match[2].trim()}`,
            body: match[3].trim()
        });
    }

    return chapters;
}

function validateChapters(chapters) {
    const expected = Array.from({ length: 24 }, (_, index) => index + 1);
    const actual = chapters.map((chapter) => chapter.chapter);
    const missing = expected.filter((chapter) => !actual.includes(chapter));
    const duplicate = actual.filter((chapter, index) => actual.indexOf(chapter) !== index);

    if (missing.length || duplicate.length || chapters.length !== 24) {
        throw new Error(`Chapter validation failed. Missing: ${missing.join(', ') || 'none'}. Duplicate: ${duplicate.join(', ') || 'none'}. Count: ${chapters.length}.`);
    }
}

function writeEnglishSource(chapters) {
    const content = [
        `# ${bookTitle}`,
        '',
        ...chapters.flatMap((chapter) => [
            `## ${chapter.title}`,
            '',
            chapter.body,
            ''
        ])
    ].join('\n').replace(/\n{3,}/g, '\n\n');

    fs.writeFileSync(englishSourcePath, `${content.trim()}\n`);
}

function writeReaderData(chapters) {
    const bookContent = [
        {
            chapter: 0,
            isChapterStart: true,
            book_title: bookTitle,
            title: bookTitle,
            content: "<div class='cover-wrapper'><img src='src/assets/images/cover.jpg' alt='The Friction of the Spark cover' class='book-cover-fullscreen'></div>",
            theme_color: '#efe8d9'
        },
        ...chapters.map((chapter) => ({
            chapter: chapter.chapter,
            isChapterStart: true,
            title: chapter.title,
            content: bodyToHtml(chapter.body)
        }))
    ];

    const output = [
        '// Generated by scripts/build_friction_english.js.',
        '// English-only reader cartridge for The Friction of the Spark.',
        'window.PocketReader = window.PocketReader || {};',
        `PocketReader.bookContent = ${JSON.stringify(bookContent, null, 4)};`,
        ''
    ].join('\n');

    fs.writeFileSync(readerDataPath, output);
}

function copyCoverAssets() {
    const coverJpgSource = path.join(contentDir, 'images', 'cover.jpg');
    const coverPngSource = path.join(contentDir, 'images', 'cover.png');
    const coverJpgTarget = path.join(repoRoot, 'src', 'assets', 'images', 'cover.jpg');
    const coverPngTarget = path.join(repoRoot, 'src', 'assets', 'images', 'cover.png');

    if (fs.existsSync(coverJpgSource)) {
        fs.copyFileSync(coverJpgSource, coverJpgTarget);
    }

    if (fs.existsSync(coverPngSource)) {
        fs.copyFileSync(coverPngSource, coverPngTarget);
    }
}

function removeNonEnglishSource() {
    if (fs.existsSync(chineseSourcePath)) {
        fs.unlinkSync(chineseSourcePath);
    }
}

function writeAudit(chapters) {
    const titleList = chapters.map((chapter) => `- ${chapter.title}`).join('\n');
    const audit = `# ${bookTitle} English Build Audit

## HOW_TO_NEW_BOOK Checklist

- Content cartridge replaced: \`src/features/reader/data.js\` now contains the generated English-only reader data.
- Cover image placed: \`src/assets/images/cover.jpg\` and \`src/assets/images/cover.png\` are copied from \`Content/TheFrictionOfTheSpark/images/\`.
- PWA icons: \`src/assets/images/icon-192.png\` and \`src/assets/images/icon-512.png\` are square crops of the cover image.
- Metadata target: \`index.html\` and \`manifest.json\` identify this book, not the previous reader sample.
- Language scope: English only. The generated cartridge has no \`title_cn\`, \`content_cn\`, \`title_id\`, or \`content_id\` fields.

## Novel Audit

- Source: rewritten Markdown chapters under \`../rewrites/\` when available; otherwise this script can rebuild from \`Content/TheFrictionOfTheSpark/en.txt\`.
- Chapter coverage: 24 of 24 chapters found and exported.
- Canon check: final act keeps Kyle's death, the pistol as systemic violence, and Eline alone at the canal with Kyle's lighter.
- Reader check: each chapter is exported as a single table-of-contents entry with paragraph HTML generated from the English manuscript.

## Chapter Inventory

${titleList}
`;

    fs.writeFileSync(auditPath, audit);
}

function main() {
    const chapters = loadChaptersFromRewrites() || parseEnglishSource();

    validateChapters(chapters);
    fs.mkdirSync(contentDir, { recursive: true });
    writeEnglishSource(chapters);
    writeReaderData(chapters);
    copyCoverAssets();
    removeNonEnglishSource();
    writeAudit(chapters);

    console.log(`Built ${bookTitle}: ${chapters.length} English chapters.`);
}

main();
